apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    kompose.cmd: kompose convert
    kompose.version: 1.30.0 (HEAD)
  creationTimestamp: null
  labels:
    io.kompose.service: todo-api
  name: todo-api
  namespace: default
spec:
  replicas: 1
  selector:
    matchLabels:
      io.kompose.service: todo-api
  strategy: {}
  template:
    metadata:
      annotations:
        kompose.cmd: kompose convert
        kompose.version: 1.30.0 (HEAD)
      creationTimestamp: null
      labels:
        io.kompose.network/todoapi-default: "true"
        io.kompose.service: todo-api
    spec:
      containers:
        - image: todo-api
          name: todo-api
          ports:
            - containerPort: 80
              hostPort: 8080
              protocol: TCP
          resources: {}
      restartPolicy: Always
status: {}
